FROM python:3.9-slim

# Have this be cached
COPY requirements.txt /
RUN pip install -r /requirements.txt

ADD . /app
WORKDIR /app

ENV FLASK_ENV=production

ENTRYPOINT python -m celery -A app.__main__.celery beat --loglevel=info


